server:
  port: 6565
  
spring:
  application:
    name: tour-agent-api
  datasource:
    url: jdbc:mysql://localhost:3306/test
    username: root
    password: srivatsan
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
  
management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include:
        - "*"
    jmx:
      exposure:
        include:
        - "*"
        
info:
  app:
    name:@project.name@
    version:@project.version@
    encoding:@project.build.sourceEncoding@
  java:
      version:@java.version@

logging:
  level:
    '[org.springframework.security]': trace    
    
    
security:
  enabled: true
   
       
