spring:
  application:
    name: api-gateway

zuul:
  routes:
    review-service:
      path: /review-service/**
      service-id: review-service 
ribbon:
  eureka:
    enabled: false

review-service:
  ribbon:
    listOfServers: http://localhost:6363/,http://localhost:6161/     
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
management:
  endpoints:
    web:
      exposure:
        include:
        - "*"    
