
spring:
  application:
    name: invoice-service
  
server:
  port: 6565
  
#eureka:
#  client:
#    service-url:
#      defaultZone: http://eureka-peer1:8765/eureka,http://eureka-peer2:8770/eureka
#       #  instance:#    lease-expiration-duration-in-seconds: 5
#    lease-renewal-interval-in-seconds: 2
    
eureka:  client:    service-url:      defaultZone: http://localhost:8761/eureka
